apiVersion: serving.knative.dev/v1

kind: Service

metadata:
  name: gcp-infra-agent
  
spec:
  template:
    spec:
      containers:
      - image: ${IMAGE}
      - env:
        - name: PORT
        - value: 9000